Collections:
  - Name: DenseCL
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
        URL: https://arxiv.org/abs/2011.09157
        Title: "Dense contrastive learning for self-supervised visual pre-training"
    README: configs/densecl/README.md

Models:
  - Name: densecl_resnet50_8xb32-coslr-200e_in1k
    In Collection: DenseCL
    Metadata:
      Epochs: 200
      Batch Size: 256
    Results: null
    Config: configs/densecl/densecl_resnet50_8xb32-coslr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/densecl/densecl_resnet50_8xb32-coslr-200e_in1k/densecl_resnet50_8xb32-coslr-200e_in1k_20220825-3078723b.pth
    Downstream:
      - resnet50_densecl-pre_8xb32-linear-steplr-100e_in1k
  - Name: resnet50_densecl-pre_8xb32-linear-steplr-100e_in1k
    Metadata:
      Epochs: 100
      Batch Size: 256
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 63.5
    Config: configs/densecl/classification/resnet50_8xb32-linear-steplr-100e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/densecl/densecl_resnet50_8xb32-coslr-200e_in1k/resnet50_linear-8xb32-steplr-100e_in1k/resnet50_linear-8xb32-steplr-100e_in1k_20220825-f0f0a579.pth
