Collections:
  - Name: Swin-Transformer V2
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - AdamW
        - Weight Decay
      Training Resources: 16x V100 GPUs
      Epochs: 300
      Batch Size: 1024
      Architecture:
        - Shift Window Multihead Self Attention
    Paper:
      URL: https://arxiv.org/abs/2111.09883
      Title: "Swin Transformer V2: Scaling Up Capacity and Resolution"
    README: configs/swin_transformer_v2/README.md

Models:
  - Name: swinv2-tiny-w8_3rdparty_in1k-256px
    Metadata:
      FLOPs: 4350000000
      Parameters: 28350000
    In Collection: Swin-Transformer V2
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 81.76
          Top 5 Accuracy: 95.87
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/swinv2-tiny-w8_3rdparty_in1k-256px_20220803-e318968f.pth
    Config: configs/swin_transformer_v2/swinv2-tiny-w8_16xb64_in1k-256px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_tiny_patch4_window8_256.pth
      Code: https://github.com/microsoft/Swin-Transformer
  - Name: swinv2-tiny-w16_3rdparty_in1k-256px
    Metadata:
      FLOPs: 4400000000
      Parameters: 28350000
    In Collection: Swin-Transformer V2
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.81
          Top 5 Accuracy: 96.23
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/swinv2-tiny-w16_3rdparty_in1k-256px_20220803-9651cdd7.pth
    Config: configs/swin_transformer_v2/swinv2-tiny-w16_16xb64_in1k-256px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_tiny_patch4_window16_256.pth
      Code: https://github.com/microsoft/Swin-Transformer
  - Name: swinv2-small-w8_3rdparty_in1k-256px
    Metadata:
      FLOPs: 8450000000
      Parameters: 49730000
    In Collection: Swin-Transformer V2
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 83.74
          Top 5 Accuracy: 96.6
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/swinv2-small-w8_3rdparty_in1k-256px_20220803-b01a4332.pth
    Config: configs/swin_transformer_v2/swinv2-small-w8_16xb64_in1k-256px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_small_patch4_window8_256.pth
      Code: https://github.com/microsoft/Swin-Transformer
  - Name: swinv2-small-w16_3rdparty_in1k-256px
    Metadata:
      FLOPs: 8570000000
      Parameters: 49730000
    In Collection: Swin-Transformer V2
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 84.13
          Top 5 Accuracy: 96.83
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/swinv2-small-w16_3rdparty_in1k-256px_20220803-b707d206.pth
    Config: configs/swin_transformer_v2/swinv2-small-w16_16xb64_in1k-256px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_small_patch4_window16_256.pth
      Code: https://github.com/microsoft/Swin-Transformer
  - Name: swinv2-base-w8_3rdparty_in1k-256px
    Metadata:
      FLOPs: 14990000000
      Parameters: 87920000
    In Collection: Swin-Transformer V2
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 84.2
          Top 5 Accuracy: 96.86
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/swinv2-base-w8_3rdparty_in1k-256px_20220803-8ff28f2b.pth
    Config: configs/swin_transformer_v2/swinv2-base-w8_16xb64_in1k-256px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_base_patch4_window8_256.pth
      Code: https://github.com/microsoft/Swin-Transformer
  - Name: swinv2-base-w16_3rdparty_in1k-256px
    Metadata:
      FLOPs: 15140000000
      Parameters: 87920000
    In Collection: Swin-Transformer V2
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 84.6
          Top 5 Accuracy: 97.05
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/swinv2-base-w16_3rdparty_in1k-256px_20220803-5a1886b7.pth
    Config: configs/swin_transformer_v2/swinv2-base-w16_16xb64_in1k-256px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_base_patch4_window16_256.pth
      Code: https://github.com/microsoft/Swin-Transformer
  - Name: swinv2-base-w16_in21k-pre_3rdparty_in1k-256px
    Metadata:
      Training Data: ImageNet-21k
      FLOPs: 15140000000
      Parameters: 87920000
    In Collection: Swin-Transformer V2
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 86.17
          Top 5 Accuracy: 97.88
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/swinv2-base-w16_in21k-pre_3rdparty_in1k-256px_20220803-8d7aa8ad.pth
    Config: configs/swin_transformer_v2/swinv2-base-w16_in21k-pre_16xb64_in1k-256px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_base_patch4_window12to16_192to256_22kto1k_ft.pth
      Code: https://github.com/microsoft/Swin-Transformer
  - Name: swinv2-base-w24_in21k-pre_3rdparty_in1k-384px
    Metadata:
      Training Data: ImageNet-21k
      FLOPs: 34070000000
      Parameters: 87920000
    In Collection: Swin-Transformer V2
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 87.14
          Top 5 Accuracy: 98.23
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/swinv2-base-w24_in21k-pre_3rdparty_in1k-384px_20220803-44eb70f8.pth
    Config: configs/swin_transformer_v2/swinv2-base-w24_in21k-pre_16xb64_in1k-384px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_base_patch4_window12to24_192to384_22kto1k_ft.pth
      Code: https://github.com/microsoft/Swin-Transformer
  - Name: swinv2-large-w16_in21k-pre_3rdparty_in1k-256px
    Metadata:
      Training Data: ImageNet-21k
      FLOPs: 33860000000
      Parameters: 196750000
    In Collection: Swin-Transformer V2
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 86.93
          Top 5 Accuracy: 98.06
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/swinv2-large-w16_in21k-pre_3rdparty_in1k-256px_20220803-c40cbed7.pth
    Config: configs/swin_transformer_v2/swinv2-large-w16_in21k-pre_16xb64_in1k-256px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_large_patch4_window12to16_192to256_22kto1k_ft.pth
      Code: https://github.com/microsoft/Swin-Transformer
  - Name: swinv2-large-w24_in21k-pre_3rdparty_in1k-384px
    Metadata:
      Training Data: ImageNet-21k
      FLOPs: 76200000000
      Parameters: 196750000
    In Collection: Swin-Transformer V2
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 87.59
          Top 5 Accuracy: 98.27
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/swinv2-large-w24_in21k-pre_3rdparty_in1k-384px_20220803-3b36c165.pth
    Config: configs/swin_transformer_v2/swinv2-large-w24_in21k-pre_16xb64_in1k-384px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_large_patch4_window12to24_192to384_22kto1k_ft.pth
      Code: https://github.com/microsoft/Swin-Transformer
  - Name: swinv2-base-w12_3rdparty_in21k-192px
    Metadata:
      Training Data: ImageNet-21k
      FLOPs: 8510000000
      Parameters: 87920000
    In Collection: Swin-Transformer V2
    Results: null
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/pretrain/swinv2-base-w12_3rdparty_in21k-192px_20220803-f7dc9763.pth
    Config: configs/swin_transformer_v2/swinv2-base-w12_8xb128_in21k-192px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_base_patch4_window12_192_22k.pth
      Code: https://github.com/microsoft/Swin-Transformer
  - Name: swinv2-large-w12_3rdparty_in21k-192px
    Metadata:
      Training Data: ImageNet-21k
      FLOPs: 19040000000
      Parameters: 196740000
    In Collection: Swin-Transformer V2
    Results: null
    Weights: https://download.openmmlab.com/mmclassification/v0/swin-v2/pretrain/swinv2-large-w12_3rdparty_in21k-192px_20220803-d9073fee.pth
    Config: configs/swin_transformer_v2/swinv2-large-w12_8xb128_in21k-192px.py
    Converted From:
      Weights: https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_large_patch4_window12_192_22k.pth
      Code: https://github.com/microsoft/Swin-Transformer
