Collections:
  - Name: MiniGPT4
    Metadata:
      Architecture:
        - Transformer
        - Gated Cross-Attention Dense
    Paper:
      Title: 'MiniGPT-4: Enhancing Vision-language Understanding with Advanced Large Language Models'
      URL: https://arxiv.org/abs/2304.10592
    README: configs/minigpt4/README.md

Models:
  - Name: minigpt-4_vicuna-7b_caption
    Metadata:
      FLOPs: null
      Parameters: 8121315072
    In Collection: MiniGPT4
    Results:
      - Task: Image Caption
        Dataset: COCO
        Metrics: null
    Weights: https://download.openmmlab.com/mmclassification/v1/minigpt4/minigpt-4_linear_vicuna7b_20230615-714b5f52.pth
    Config: configs/minigpt4/minigpt-4_vicuna-7b_caption.py
    Converted From:
      Weights: https://github.com/Vision-CAIR/MiniGPT-4/tree/main
      Code: https://github.com/Vision-CAIR/MiniGPT-4/tree/main
  - Name: minigpt-4_baichuan-7b_caption
    Metadata:
      FLOPs: null
      Parameters: 8094769024
    In Collection: MiniGPT4
    Results:
      - Task: Image Caption
        Dataset: COCO
        Metrics: null
    Weights: https://download.openmmlab.com/mmclassification/v1/minigpt4/minigpt-4_linear_baichuan7b_20231011-5dca7ed6.pth
    Config: configs/minigpt4/minigpt-4_baichuan-7b_caption.py
