Collections:
  - Name: BarlowTwins
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - LARS
      Training Resources: 8x A100 GPUs
      Architecture:
        - ResNet
        - BarlowTwins
    Paper:
        URL: https://arxiv.org/abs/2103.03230
        Title: "Barlow Twins: Self-Supervised Learning via Redundancy Reduction"
    README: configs/barlowtwins/README.md

Models:
  - Name: barlowtwins_resnet50_8xb256-coslr-300e_in1k
    In Collection: BarlowTwins
    Metadata:
      Epochs: 300
      Batch Size: 2048
    Results: null
    Config: configs/barlowtwins/barlowtwins_resnet50_8xb256-coslr-300e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/barlowtwins/barlowtwins_resnet50_8xb256-coslr-300e_in1k/barlowtwins_resnet50_8xb256-coslr-300e_in1k_20220825-57307488.pth
    Downstream:
      - resnet50_barlowtwins-pre_8xb32-linear-coslr-100e_in1k
  - Name: resnet50_barlowtwins-pre_8xb32-linear-coslr-100e_in1k
    Metadata:
      Epochs: 100
      Batch Size: 256
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 71.8
    Config: configs/barlowtwins/classification/resnet50_8xb32-linear-coslr-100e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/barlowtwins/barlowtwins_resnet50_8xb256-coslr-300e_in1k/resnet50_linear-8xb32-coslr-100e_in1k/resnet50_linear-8xb32-coslr-100e_in1k_20220825-52fde35f.pth
