Collections:
  - Name: SwAV
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - LARS
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
        - SwAV
    Paper:
        URL: https://arxiv.org/abs/2006.09882
        Title: "Unsupervised Learning of Visual Features by Contrasting Cluster Assignments"
    README: configs/swav/README.md

Models:
  - Name: swav_resnet50_8xb32-mcrop-coslr-200e_in1k-224px-96px
    In Collection: SwAV
    Metadata:
      Epochs: 200
      Batch Size: 256
    Results: null
    Config: configs/swav/swav_resnet50_8xb32-mcrop-coslr-200e_in1k-224px-96px.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/swav/swav_resnet50_8xb32-mcrop-2-6-coslr-200e_in1k-224-96/swav_resnet50_8xb32-mcrop-2-6-coslr-200e_in1k-224-96_20220825-5b3fc7fc.pth
    Downstream:
      - resnet50_swav-pre_8xb32-linear-coslr-100e_in1k
  - Name: resnet50_swav-pre_8xb32-linear-coslr-100e_in1k
    Metadata:
      Epochs: 100
      Batch Size: 256
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 70.5
    Config: configs/swav/benchmarks/resnet50_8xb32-linear-coslr-100e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/swav/swav_resnet50_8xb32-mcrop-2-6-coslr-200e_in1k-224-96/resnet50_linear-8xb32-coslr-100e_in1k/resnet50_linear-8xb32-coslr-100e_in1k_20220825-80341e08.pth
