Collections:
  - Name: Twins
    Metadata:
      Training Data: ImageNet-1k
      Architecture:
        - Global Subsampled Attention
        - Locally Grouped SelfAttention
        - Conditional Position Encoding
        - Pyramid Vision Transformer
    Paper:
      URL: http://arxiv-export-lb.library.cornell.edu/abs/2104.13840
      Title: "Twins: Revisiting the Design of Spatial Attention in Vision Transformers"
    README: configs/twins/README.md
    Code:
      URL: https://github.com/open-mmlab/mmclassification/blob/v0.20.1/mmcls/models/backbones/twins.py
      Version: v0.20.1

Models:
  - Name: twins-pcpvt-small_3rdparty_8xb128_in1k
    Metadata:
      FLOPs: 3670000000        # 3.67G
      Parameters: 24110000     # 24.11M
    In Collection: Twins
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 81.14
          Top 5 Accuracy: 95.69
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/twins/twins-pcpvt-small_3rdparty_8xb128_in1k_20220126-ef23c132.pth
    Config: configs/twins/twins-pcpvt-small_8xb128_in1k.py
    Converted From:
      Weights: https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vt3p-weights/twins_pcpvt_small-e70e7e7a.pth
      Code: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/twins.py
  - Name: twins-pcpvt-base_3rdparty_8xb128_in1k
    Metadata:
      FLOPs: 6450000000        # 6.45G
      Parameters: 43830000     # 43.83M
    In Collection: Twins
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.66
          Top 5 Accuracy: 96.26
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/twins/twins-pcpvt-base_3rdparty_8xb128_in1k_20220126-f8c4b0d5.pth
    Config: configs/twins/twins-pcpvt-base_8xb128_in1k.py
    Converted From:
      Weights: https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vt3p-weights/twins_pcpvt_small-e70e7e7a.pth
      Code: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/twins.py
  - Name: twins-pcpvt-large_3rdparty_16xb64_in1k
    Metadata:
      FLOPs: 9510000000           # 9.51G
      Parameters: 60990000        # 60.99M
    In Collection: Twins
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 83.09
          Top 5 Accuracy: 96.59
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/twins/twins-pcpvt-large_3rdparty_16xb64_in1k_20220126-c1ef8d80.pth
    Config: configs/twins/twins-pcpvt-large_16xb64_in1k.py
    Converted From:
      Weights: https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vt3p-weights/twins_pcpvt_small-e70e7e7a.pth
      Code: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/twins.py
  - Name: twins-svt-small_3rdparty_8xb128_in1k
    Metadata:
      FLOPs: 2820000000            # 2.82G
      Parameters: 24060000         # 24.06M
    In Collection: Twins
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 81.77
          Top 5 Accuracy: 95.57
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/twins/twins-svt-small_3rdparty_8xb128_in1k_20220126-8fe5205b.pth
    Config: configs/twins/twins-svt-small_8xb128_in1k.py
    Converted From:
      Weights: https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vt3p-weights/twins_pcpvt_small-e70e7e7a.pth
      Code: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/twins.py
  - Name: twins-svt-base_8xb128_3rdparty_in1k
    Metadata:
      FLOPs: 8350000000           # 8.35G
      Parameters: 56070000        # 56.07M
    In Collection: Twins
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 83.13
          Top 5 Accuracy: 96.29
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/twins/twins-svt-base_3rdparty_8xb128_in1k_20220126-e31cc8e9.pth
    Config: configs/twins/twins-svt-base_8xb128_in1k.py
    Converted From:
      Weights: https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vt3p-weights/twins_pcpvt_small-e70e7e7a.pth
      Code: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/twins.py
  - Name: twins-svt-large_3rdparty_16xb64_in1k
    Metadata:
      FLOPs: 14820000000          # 14.82G
      Parameters: 99270000        # 99.27M
    In Collection: Twins
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 83.60
          Top 5 Accuracy: 96.50
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/twins/twins-svt-large_3rdparty_16xb64_in1k_20220126-4817645f.pth
    Config: configs/twins/twins-svt-large_16xb64_in1k.py
    Converted From:
      Weights: https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vt3p-weights/twins_pcpvt_small-e70e7e7a.pth
      Code: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/twins.py
