Collections:
  - Name: Shufflenet V1
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
        - No BN decay
      Training Resources: 8x 1080 GPUs
      Epochs: 300
      Batch Size: 1024
      Architecture:
        - Shufflenet V1
    Paper: https://openaccess.thecvf.com/content_cvpr_2018/html/Zhang_ShuffleNet_An_Extremely_CVPR_2018_paper.html
    README: configs/shufflenet_v1/README.md

Models:
  - Name: shufflenet_v1_1x_b64x16_linearlr_bn_nowd_imagenet
    Metadata:
      FLOPs: 146000000
      Parameters: 1870000
    In Collection: Shufflenet V1
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 68.13
          Top 5 Accuracy: 87.81
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/shufflenet_v1/shufflenet_v1_batch1024_imagenet_20200804-5d6cec73.pth
    Config: configs/shufflenet_v1/shufflenet_v1_1x_b64x16_linearlr_bn_nowd_imagenet.py
