Collections:
  - Name: BYOL
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - LARS
      Training Resources: 8x V100 GPUs (b256), 16x A100-80G GPUs (b4096)
      Architecture:
        - ResNet
        - BYOL
    Paper:
        URL: https://arxiv.org/abs/2006.07733
        Title: "Bootstrap your own latent: A new approach to self-supervised Learning"
    README: configs/byol/README.md

Models:
  - Name: byol_resnet50_16xb256-coslr-200e_in1k
    In Collection: BYOL
    Metadata:
      Epochs: 200
      Batch Size: 4096
    Results: null
    Config: configs/byol/byol_resnet50_16xb256-coslr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/byol/byol_resnet50_16xb256-coslr-200e_in1k/byol_resnet50_16xb256-coslr-200e_in1k_20220825-de817331.pth
    Downstream:
      - resnet50_byol-pre_8xb512-linear-coslr-90e_in1k
  - Name: resnet50_byol-pre_8xb512-linear-coslr-90e_in1k
    In Collection: BYOL
    Metadata:
      Epochs: 90
      Batch Size: 4096
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 71.8
    Config: configs/byol/classification/resnet50_8xb512-linear-coslr-90e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/byol/byol_resnet50_16xb256-coslr-200e_in1k/resnet50_linear-8xb512-coslr-90e_in1k/resnet50_linear-8xb512-coslr-90e_in1k_20220825-7596c6f5.pth
